import type { Course, DebateTopic, User, UserProgress } from './types'

// Mock user
export const mockUser: User = {
  id: '1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
}

// Mock user progress
export const mockUserProgress: UserProgress = {
  userId: '1',
  totalXp: 2450,
  streak: 7,
  completedCourses: 3,
  completedDebates: 12,
  level: 'B1',
}

// Mock courses
export const mockCourses: Course[] = [
  {
    id: 'c1',
    title: 'Daily Conversations',
    description: 'Master everyday English for daily interactions',
    level: 'A1',
    category: 'Beginner',
    duration: 45,
    lessons: 15,
    instructor: 'Sarah Smith',
    xpReward: 100,
    enrollmentCount: 1250,
    rating: 4.8,
    ratingCount: 324,
    createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c2',
    title: 'Business English Basics',
    description: 'Essential vocabulary and phrases for business settings',
    level: 'A2',
    category: 'Business',
    duration: 60,
    lessons: 20,
    instructor: 'Michael Chen',
    xpReward: 150,
    enrollmentCount: 980,
    rating: 4.7,
    ratingCount: 256,
    createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c3',
    title: 'Professional Presentations',
    description: 'Learn to deliver engaging presentations in English',
    level: 'B1',
    category: 'Business',
    duration: 75,
    lessons: 18,
    instructor: 'Emma Wilson',
    xpReward: 200,
    enrollmentCount: 650,
    rating: 4.9,
    ratingCount: 189,
    isTrending: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c4',
    title: 'Travel English',
    description: 'Communicate confidently while traveling abroad',
    level: 'A1',
    category: 'Travel',
    duration: 50,
    lessons: 16,
    instructor: 'James Rodriguez',
    xpReward: 120,
    enrollmentCount: 1450,
    rating: 4.6,
    ratingCount: 412,
    createdAt: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c5',
    title: 'Advanced Vocabulary',
    description: 'Expand your vocabulary with advanced topics',
    level: 'B2',
    category: 'Advanced',
    duration: 90,
    lessons: 25,
    instructor: 'Dr. Lisa Park',
    xpReward: 250,
    enrollmentCount: 420,
    rating: 4.8,
    ratingCount: 134,
    createdAt: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c6',
    title: 'Listening Skills',
    description: 'Improve your English listening comprehension',
    level: 'A2',
    category: 'Skills',
    duration: 55,
    lessons: 17,
    instructor: 'Tom Harrison',
    xpReward: 130,
    enrollmentCount: 890,
    rating: 4.7,
    ratingCount: 267,
    createdAt: new Date(Date.now() - 50 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c7',
    title: 'Idioms and Expressions',
    description: 'Learn natural English idioms and colloquial expressions',
    level: 'B1',
    category: 'Vocabulary',
    duration: 65,
    lessons: 19,
    instructor: 'Rachel Green',
    xpReward: 180,
    enrollmentCount: 710,
    rating: 4.8,
    ratingCount: 198,
    createdAt: new Date(Date.now() - 35 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c8',
    title: 'Interview Preparation',
    description: 'Prepare for job interviews in English',
    level: 'B1',
    category: 'Career',
    duration: 70,
    lessons: 21,
    instructor: 'David Martinez',
    xpReward: 210,
    enrollmentCount: 560,
    rating: 4.9,
    ratingCount: 145,
    isTrending: true,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c9',
    title: 'Grammar Mastery',
    description: 'Master English grammar rules and exceptions',
    level: 'A2',
    category: 'Grammar',
    duration: 80,
    lessons: 24,
    instructor: 'Professor Alan Brown',
    xpReward: 160,
    enrollmentCount: 1100,
    rating: 4.7,
    ratingCount: 334,
    createdAt: new Date(Date.now() - 48 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c10',
    title: 'Pronunciation Perfect',
    description: 'Refine your English pronunciation and accent',
    level: 'A1',
    category: 'Skills',
    duration: 40,
    lessons: 12,
    instructor: 'Sophie Turner',
    xpReward: 110,
    enrollmentCount: 1320,
    rating: 4.8,
    ratingCount: 298,
    createdAt: new Date(Date.now() - 58 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c11',
    title: 'Cultural Conversations',
    description: 'Understand cultural nuances in English communication',
    level: 'B2',
    category: 'Culture',
    duration: 85,
    lessons: 22,
    instructor: 'Maria Garcia',
    xpReward: 230,
    enrollmentCount: 480,
    rating: 4.8,
    ratingCount: 167,
    createdAt: new Date(Date.now() - 32 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'c12',
    title: 'Fluency Bootcamp',
    description: 'Intensive training to achieve fluent English speech',
    level: 'B1',
    category: 'Advanced',
    duration: 100,
    lessons: 28,
    instructor: 'James Collins',
    xpReward: 280,
    enrollmentCount: 340,
    rating: 4.9,
    ratingCount: 112,
    isTrending: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

// Mock debate topics
export const mockDebateTopics: DebateTopic[] = [
  {
    id: 'd1',
    title: 'Remote Work vs Office',
    description: 'Is remote work more productive than working in an office?',
    category: 'Work & Career',
    level: 'B1',
    proArguments: [
      'Eliminates commute time',
      'Better work-life balance',
      'Fewer distractions for some',
      'Cost savings for employees',
    ],
    conArguments: [
      'Less team collaboration',
      'Isolation and loneliness',
      'Communication challenges',
      'Harder to train new employees',
    ],
    vocabularyTips: ['productive', 'commute', 'collaboration', 'isolation', 'efficiency'],
    phrasesSuggested: [
      'I believe that...',
      'On the other hand...',
      'In my opinion...',
      'However, we should consider...',
    ],
    duration: 15,
    difficulty: 'medium',
    participants: 234,
    rating: 4.7,
    isFeatured: true,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd2',
    title: 'Technology and Society',
    description: 'Is technology making us happier or more stressed?',
    category: 'Social Issues',
    level: 'B2',
    proArguments: [
      'Connects people globally',
      'Improves healthcare',
      'Increases productivity',
      'Provides access to education',
    ],
    conArguments: [
      'Increases anxiety and depression',
      'Less face-to-face interaction',
      'Privacy concerns',
      'Addiction to devices',
    ],
    vocabularyTips: ['anxiety', 'depression', 'connectivity', 'implications', 'advancement'],
    phrasesSuggested: [
      'From a practical standpoint...',
      'This raises the question of...',
      'We cannot ignore the fact that...',
      'In light of recent developments...',
    ],
    duration: 20,
    difficulty: 'hard',
    participants: 156,
    rating: 4.8,
    isFeatured: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd3',
    title: 'Climate Change Action',
    description: 'Should governments enforce strict climate regulations?',
    category: 'Environment',
    level: 'B1',
    proArguments: [
      'Protects future generations',
      'Prevents environmental disasters',
      'Creates green jobs',
      'Improves public health',
    ],
    conArguments: [
      'Increases costs for businesses',
      'May harm economy',
      'China and India need to act first',
      'Technology will solve the problem',
    ],
    vocabularyTips: ['regulations', 'environmental', 'enforcement', 'sustainability', 'emissions'],
    phrasesSuggested: [
      'I understand your point, but...',
      'The evidence suggests that...',
      'We should take into account...',
      'This is supported by...',
    ],
    duration: 18,
    difficulty: 'medium',
    participants: 412,
    rating: 4.6,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd4',
    title: 'Social Media Impact',
    description: 'Should social media be regulated by governments?',
    category: 'Social Issues',
    level: 'A2',
    proArguments: [
      'Protects children',
      'Prevents misinformation',
      'Protects personal data',
      'Reduces cyberbullying',
    ],
    conArguments: [
      'Restricts free speech',
      'Difficult to enforce',
      'Companies can self-regulate',
      'Different cultures have different values',
    ],
    vocabularyTips: ['misinformation', 'regulate', 'cyberbullying', 'data protection', 'regulate'],
    phrasesSuggested: [
      'I think that...',
      'Because of...',
      'For example...',
      'I disagree because...',
    ],
    duration: 12,
    difficulty: 'easy',
    participants: 589,
    rating: 4.5,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd5',
    title: 'Education System Reform',
    description: 'Should traditional grading systems be replaced with alternative assessment?',
    category: 'Education',
    level: 'B1',
    proArguments: [
      'Grades don\'t reflect real knowledge',
      'Reduces student anxiety',
      'Encourages deeper learning',
      'Better for diverse learners',
    ],
    conArguments: [
      'Grading is objective and fair',
      'Universities need standardized metrics',
      'Difficult to implement',
      'Employers understand traditional grades',
    ],
    vocabularyTips: ['assessment', 'alternative', 'standardized', 'metrics', 'implementation'],
    phrasesSuggested: [
      'The main reason is...',
      'Furthermore...',
      'It\'s important to note that...',
      'As a result...',
    ],
    duration: 16,
    difficulty: 'medium',
    participants: 267,
    rating: 4.7,
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'd6',
    title: 'Universal Basic Income',
    description: 'Would Universal Basic Income solve poverty?',
    category: 'Economics',
    level: 'B2',
    proArguments: [
      'Guarantees basic living standards',
      'Reduces poverty and inequality',
      'Simplifies welfare systems',
      'Provides entrepreneurship opportunity',
    ],
    conArguments: [
      'Too expensive to implement',
      'Would cause inflation',
      'Reduces work incentive',
      'Better to target assistance',
    ],
    vocabularyTips: ['Universal Basic Income', 'inequality', 'poverty', 'inflation', 'incentive'],
    phrasesSuggested: [
      'The proponents argue that...',
      'While this may be true...',
      'The underlying assumption is...',
      'This perspective overlooks...',
    ],
    duration: 22,
    difficulty: 'hard',
    participants: 134,
    rating: 4.8,
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
]
